version: 0.1.{build}
image: Visual Studio 2017

clone_folder: c:\projects\python_wrapper

environment:
  PYTHONPATH: c:\projects\python_wrapper
  PATH: C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%
  PYTHON: C:\Python36-x64\python.exe
  PIP: C:\Python36-x64\Scripts\pip.exe

install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools wheel coverage mypy flake8 twine pylint pygount

before_build:
  - pygount irbis -f summary

build_script:
  - cd c:\projects\python_wrapper
  - python -m flake8 irbis test.py
  - python -m mypy irbis test.py
  - python -m pylint irbis test.py
